#!/usr/bin/env node

if (!require('assert').strict) {
	console.error("We require Node.js version 10 or later; you're using " + process.version);
	process.exit(1);
}

var execSync = require('child_process').execSync;
var fs = require('fs');

process.chdir(__dirname);

try {
	require.resolve('@babel/core');
} catch (e) {
	console.log('Installing dependencies...');
	execSync('npm install', {stdio: 'inherit'});
}

try {
	require.resolve('./config/config');
} catch (err) {
	if (err.code !== 'MODULE_NOT_FOUND') throw err; // should never happen

	console.log('config.js does not exist. Creating one with default settings...');
	fs.writeFileSync(
		'config/config.js',
		fs.readFileSync('config/config-example.js')
	);
}

// Copia config para play.pokemonshowdown.com/config/
try {
	var playConfig = __dirname + '/play.pokemonshowdown.com/config';
	fs.mkdirSync(playConfig, { recursive: true });
	var configSrc = __dirname + '/config/config.js';
	var configContent;
	if (fs.existsSync(configSrc)) {
		configContent = fs.readFileSync(configSrc, 'utf8');
	} else {
		var routes = {};
		try { routes = JSON.parse(fs.readFileSync(__dirname + '/config/routes.json', 'utf8')); } catch (e) {}
		configContent = fs.readFileSync(__dirname + '/config/config-example.js', 'utf8');
		configContent = configContent.replace(/Config\.defaultserver\s*=\s*\{[\s\S]*?\};/,
			"Config.defaultserver={id:'ocbmons',host:'ocbmon-showdown.onrender.com',port:443,httpport:80,altport:80,registered:false};");
		if (routes.client) configContent += "\nConfig.routes=" + JSON.stringify(routes) + ";\n";
	}
	fs.writeFileSync(playConfig + '/config.js', configContent);
	var testSrc = __dirname + '/config/config-test.js';
	if (fs.existsSync(testSrc)) fs.copyFileSync(testSrc, playConfig + '/config-test.js');
	fs.writeFileSync(playConfig + '/colors.json', fs.existsSync(__dirname + '/config/colors.json') ? fs.readFileSync(__dirname + '/config/colors.json') : '{}');
} catch (e) {
	console.error('Erro ao copiar config:', e.message);
	throw e;
}

var options = {cwd: __dirname, stdio: 'inherit'};
var full = '';

switch (process.argv[2] || '') {
case 'full':
	execSync(`node ./build-tools/build-indexes`, options);
	execSync(`node ./build-tools/build-learnsets`, options);
	execSync(`node ./build-tools/build-minidex`, options);
	full = ' full';
	break;
case 'indexes':
	execSync(`node ./build-tools/build-indexes`, options);
	break;
case 'learnsets':
	execSync(`node ./build-tools/build-learnsets`, options);
	break;
case 'minidex':
case 'sprites':
	execSync(`node ./build-tools/build-minidex`, options);
	break;
case 'commands':
	execSync(`node ./build-tools/build-commands`, options);
	break;
case 'replays':
	execSync(`node ./build-tools/build-replays`, options);
	process.exit();
	break;
case 'test-only':

	break;
case '':
	break;
default:
	console.log(`Unrecognized command ${process.argv[2]}`);
	process.exit();
	break;
}

execSync(`node ./build-tools/update` + full, options);

if (full) {
	try {
		execSync(`node ./build-tools/build-commands`, options);
		execSync(`node ./build-tools/build-replays`, options);
	} catch (e) {
		console.error(e);
	}
}
