#!/usr/bin/env node
'use strict';

const fs = require("fs");
const path = require('path');
const child_process = require("child_process");

const rootDir = path.resolve(__dirname, '..');
process.chdir(rootDir);

// Usa servidor local (workspace) se existir e tiver dist/; senão usa caches/pokemon-showdown
const localServer = path.resolve(rootDir, '..', 'pokemon-showdown');
const cacheServer = path.resolve(rootDir, 'caches', 'pokemon-showdown');
const useLocalServer = fs.existsSync(localServer) && fs.existsSync(path.join(localServer, 'dist'));

let serverRoot;
if (useLocalServer) {
	serverRoot = localServer;
	console.log('Using local server: ' + serverRoot);
} else {
	const cachesDir = path.join(rootDir, 'caches');
	fs.mkdirSync(cachesDir, { recursive: true });
	const pkgJson = path.join(cacheServer, 'package.json');
	let justCloned = false;
	if (!fs.existsSync(pkgJson)) {
		if (fs.existsSync(cacheServer)) {
			fs.rmSync(cacheServer, { recursive: true, force: true });
		}
		console.log('Cloning ocbmon-showdown into caches...');
		child_process.execSync(
			'git clone --depth 1 https://github.com/feneto7/ocbmon-showdown.git pokemon-showdown',
			{ cwd: cachesDir, stdio: 'inherit' }
		);
		justCloned = true;
	}
	if (!fs.existsSync(pkgJson)) {
		throw new Error('caches/pokemon-showdown: clone failed or missing package.json');
	}
	if (!fs.existsSync(path.join(cacheServer, 'dist'))) {
		process.stdout.write('Compilando servidor no cache... ');
		child_process.execSync('npm ci && node build', { cwd: cacheServer, stdio: 'inherit' });
		fs.mkdirSync(path.join(cacheServer, 'dist/data/mods'), { recursive: true });
		console.log('DONE');
	} else if (!justCloned) {
		process.stdout.write('Syncing data from Git repository... ');
		try {
			child_process.execSync('git pull --ff-only', { cwd: cacheServer, stdio: 'inherit' });
		} catch {
			// shallow ou rede: segue com dist atual
		}
		child_process.execSync('npm ci && node build', { cwd: cacheServer, stdio: 'inherit' });
		console.log('DONE');
	}
	serverRoot = cacheServer;
}

const Dex = require(path.join(serverRoot, 'dist/sim/dex')).Dex;
const CompoundWordNames = require(path.join(serverRoot, 'dist/data/aliases')).CompoundWordNames;
const toID = Dex.toID;
process.stdout.write("Loading gen 6 data... ");
Dex.includeData();
console.log("DONE");

function es3stringify(obj) {
	const buf = JSON.stringify(obj);
	return buf.replace(/"([A-Za-z][A-Za-z0-9]*)":/g, (fullMatch, key) => (
		['return', 'new', 'delete'].includes(key) ? fullMatch : `${key}:`
	));
}

function requireNoCache(pathSpec) {
	delete require.cache[require.resolve(pathSpec)];
	return require(pathSpec);
}

/*********************************************************
 * Build search-index.js
 *********************************************************/

{
	process.stdout.write("Building `data/search-index.js`... ");

	let index = [];

	index = index.concat(Object.keys(Dex.data.Pokedex).map(x => x + ' pokemon'));
	index = index.concat(Object.keys(Dex.data.Moves).map(x => x + ' move'));
	index = index.concat(Object.keys(Dex.data.Items).map(x => x + ' item'));
	index = index.concat(Object.keys(Dex.data.Abilities).map(x => x + ' ability'));
	index = index.concat(Object.keys(Dex.data.TypeChart).map(x => toID(x) + ' type'));
	index = index.concat(['physical', 'special', 'status'].map(x => toID(x) + ' category'));
	index = index.concat([
		'monster', 'water1', 'bug', 'flying', 'field', 'fairy', 'grass', 'humanlike', 'water3', 'mineral', 'amorphous', 'water2', 'ditto', 'dragon', 'undiscovered',
	].map(x => toID(x) + ' egggroup'));
	index = index.concat([
		'ou', 'uu', 'ru', 'nu', 'pu', 'zu', 'lc', 'nfe', 'uber', 'uubl', 'rubl', 'nubl', 'publ', 'zubl', 'cap', 'caplc', 'capnfe',
	].map(x => toID(x) + ' tier'));

	const BattleArticleTitles = {};

	try {
		for (const file of fs.readdirSync('../dex.pokemonshowdown.com/articles/')) {
			if (file.endsWith('.md')) {
				const id = file.slice(0, -3);
				const contents = '' + fs.readFileSync('../dex.pokemonshowdown.com/articles/' + file);
				if (contents.startsWith('# ')) {
					const title = contents.slice(2, contents.indexOf('\n'));
					if (title !== id.charAt(0).toUpperCase() + id.slice(1)) {
						BattleArticleTitles[id] = title;
					}
				}
				index.push('' + id + ' article');
			}
		}
	} catch {
		console.log('\n(WARNING: NO ARTICLES)');
	}
	index.push('pokemon article');
	index.push('moves article');

	const compoundTable = new Map(CompoundWordNames.map(word => [toID(word), word]));
	// generate aliases
	function generateAlias(id, name, type) {
		name = compoundTable.get(id) || name;
		if (type === 'pokemon' && !compoundTable.has(id)) {
			const species = Dex.species.get(id);
			const baseid = toID(species.baseSpecies);
			if (baseid !== id) {
				name = (compoundTable.get(baseid) || species.baseSpecies) + ' ' + species.forme;
			}
		}
		if (name.endsWith(' Mega-X') || name.endsWith(' Mega-Y')) {
			index.push('mega' + toID(name.slice(0, -7) + name.slice(-1)) + ' ' + type + ' ' + id + ' 0');
			index.push('m' + toID(name.slice(0, -7) + name.slice(-1)) + ' ' + type + ' ' + id + ' 0');
			index.push('mega' + toID(name.slice(-1)) + ' ' + type + ' ' + id + ' ' + toID(name.slice(0, -7)).length);
		} else if (name.endsWith(' Mega')) {
			index.push('mega' + toID(name.slice(0, -5)) + ' ' + type + ' ' + id + ' 0');
			index.push('m' + toID(name.slice(0, -5)) + ' ' + type + ' ' + id + ' 0');
		} else if (name.endsWith(' Alola')) {
			index.push('alolan' + toID(name.slice(0, -6)) + ' ' + type + ' ' + id + ' 0');
		} else if (name.endsWith(' Galar')) {
			index.push('galarian' + toID(name.slice(0, -6)) + ' ' + type + ' ' + id + ' 0');
		} else if (name.endsWith(' Hisui')) {
			index.push('hisuian' + toID(name.slice(0, -6)) + ' ' + type + ' ' + id + ' 0');
		}
		const fullSplit = name.split(/ |-/).map(toID);
		if (fullSplit.length < 2) return;
		const fullAcronym = fullSplit.map(x => x.charAt(0)).join('') + fullSplit.at(-1).slice(1);
		index.push('' + fullAcronym + ' ' + type + ' ' + id + ' 0');
		for (let i = 1; i < fullSplit.length; i++) {
			index.push('' + fullSplit.slice(i).join('') + ' ' + type + ' ' + id + ' ' + fullSplit.slice(0, i).join('').length);
		}

		const spaceSplit = name.split(' ').map(toID);
		if (spaceSplit.length !== fullSplit.length) {
			const spaceAcronym = spaceSplit.map(x => x.charAt(0)).join('') + spaceSplit.at(-1).slice(1);
			if (spaceAcronym !== fullAcronym) {
				index.push('' + spaceAcronym + ' ' + type + ' ' + id + ' 0');
			}
		}
	}
	for (const id in Dex.data.Pokedex) {
		const name = Dex.data.Pokedex[id].name;
		if (Dex.data.Pokedex[id].isCosmeticForme) continue;
		generateAlias(id, name, 'pokemon');
	}
	for (const id in Dex.data.Moves) {
		const name = Dex.data.Moves[id].name;
		generateAlias(id, name, 'move');
	}
	for (const id in Dex.data.Items) {
		const name = Dex.data.Items[id].name;
		generateAlias(id, name, 'item');
	}
	for (const id in Dex.data.Abilities) {
		const name = Dex.data.Abilities[id].name;
		generateAlias(id, name, 'ability');
	}

	// hardcode ultra beasts
	const ultraBeasts = {
		ub01symbiont: "nihilego",
		ub02absorption: "buzzwole",
		ub02beauty: "pheromosa",
		ub03lightning: "xurkitree",
		ub04blade: "kartana",
		ub04blaster: "celesteela",
		ub05glutton: "guzzlord",
		ubburst: "blacephalon",
		ubassembly: "stakataka",
		ubadhesive: "poipole",
		ubstinger: "naganadel",
	};
	for (const [ubCode, id] of Object.entries(ultraBeasts)) {
		index.push(`${ubCode} pokemon ${id} 0`);
	}

	index.sort();

	// manually rearrange
	index[index.indexOf('grass type')] = 'grass egggroup';
	index[index.indexOf('grass egggroup')] = 'grass type';

	index[index.indexOf('fairy type')] = 'fairy egggroup';
	index[index.indexOf('fairy egggroup')] = 'fairy type';

	index[index.indexOf('flying type')] = 'flying egggroup';
	index[index.indexOf('flying egggroup')] = 'flying type';

	index[index.indexOf('dragon type')] = 'dragon egggroup';
	index[index.indexOf('dragon egggroup')] = 'dragon type';

	index[index.indexOf('bug type')] = 'bug egggroup';
	index[index.indexOf('bug egggroup')] = 'bug type';

	index[index.indexOf('psychic type')] = 'psychic move';
	index[index.indexOf('psychic move')] = 'psychic type';

	index[index.indexOf('ditto pokemon')] = 'ditto egggroup';
	index[index.indexOf('ditto egggroup')] = 'ditto pokemon';

	const BattleSearchIndex = index.map(x => {
		x = x.split(' ');
		if (x.length > 3) {
			x[3] = Number(x[3]);
			x[2] = index.indexOf(x[2] + ' ' + x[1]);
		}
		return x;
	});

	const BattleSearchIndexOffset = BattleSearchIndex.map(entry => {
		const id = entry[0];
		let name = '';
		switch (entry[1]) {
		case 'pokemon': name = Dex.species.get(id).name; break;
		case 'move': name = Dex.moves.get(id).name; break;
		case 'item': name = Dex.items.get(id).name; break;
		case 'ability': name = Dex.abilities.get(id).name; break;
		case 'article': name = BattleArticleTitles[id] || ''; break;
		}
		let res = '';
		let nonAlnum = 0;
		for (let i = 0, j = 0; i < id.length; i++, j++) {
			while (!/[a-zA-Z0-9]/.test(name[j])) {
				j++;
				nonAlnum++;
			}
			res += nonAlnum;
		}
		if (nonAlnum) return res;
		return '';
	});

	const BattleSearchCountIndex = {};
	for (const type in Dex.data.TypeChart) {
		BattleSearchCountIndex[type + ' move'] = Object.keys(Dex.data.Moves)
			.filter(id => (Dex.data.Moves[id].type === type)).length;
	}

	for (const type in Dex.data.TypeChart) {
		BattleSearchCountIndex[type + ' pokemon'] = Object.keys(Dex.data.Pokedex)
			.filter(id => (
				!Dex.data.Pokedex[id].isCosmeticForme &&
				Dex.data.Pokedex[id].types.indexOf(type) >= 0
			)).length;
	}

	let buf = '// DO NOT EDIT - automatically built with build-tools/build-indexes\n\n';

	buf += 'exports.BattleSearchIndex = ' + JSON.stringify(BattleSearchIndex) + ';\n\n';

	buf += 'exports.BattleSearchIndexOffset = ' + JSON.stringify(BattleSearchIndexOffset) + ';\n\n';

	buf += 'exports.BattleSearchCountIndex = ' + JSON.stringify(BattleSearchCountIndex) + ';\n\n';

	buf += 'exports.BattleArticleTitles = ' + JSON.stringify(BattleArticleTitles) + ';\n\n';

	fs.writeFileSync('play.pokemonshowdown.com/data/search-index.js', buf);
}

console.log("DONE");

/*********************************************************
 * Build teambuilder-tables.js (GEN 9 ONLY)
 *********************************************************/

process.stdout.write("Building `data/teambuilder-tables.js`... ");

{
	const BattleTeambuilderTable = {};
	let buf = '// DO NOT EDIT - automatically built with build-tools/build-indexes\n\n';

	const gen = 'gen9';
	const genNum = 9;

	const pokemon = Object.keys(Dex.data.Pokedex).sort();

	const tierTable = {};
	const overrideTier = {};

	for (const id of pokemon) {
		const species = Dex.mod(gen).species.get(id);
		if (!species.exists) continue;
		if (species.gen > genNum) continue;

		const tier = species.tier || 'Illegal';
		overrideTier[id] = tier;

		if (!tierTable[tier]) tierTable[tier] = [];
		tierTable[tier].push(id);
	}

	const tiers = [];
	const items = [];
	const formatSlices = {};

	BattleTeambuilderTable.tiers = tiers;
	BattleTeambuilderTable.items = items;
	BattleTeambuilderTable.overrideTier = overrideTier;
	BattleTeambuilderTable.formatSlices = formatSlices;

	const tierOrder = [
		"AG", "Uber", "OU", "UUBL", "UU", "RUBL", "RU",
		"NUBL", "NU", "PUBL", "PU", "ZUBL", "ZU",
		"New", "NFE", "LC", "Unreleased"
	];

	for (const tier of tierOrder) {
		if (!tierTable[tier]) continue;
		formatSlices[tier] = tiers.length;
		tiers.push(['header', tier]);
		tiers.push(...tierTable[tier]);
	}
	// Preenche formatSlices para tiers inexistentes (evita slice(undefined) = array inteiro no cliente e duplicatas na lista)
	for (const tier of tierOrder) {
		if (formatSlices[tier] === undefined) formatSlices[tier] = tiers.length;
	}

	// Items
	const itemList = Object.keys(Dex.data.Items).sort();

	const greatItems = [['header', "Items"]];

	for (const id of itemList) {
		const item = Dex.mod(gen).items.get(id);
		if (!item.exists) continue;
		if (item.gen > genNum) continue;
		if (item.isNonstandard) continue;
		greatItems.push(id);
	}

	items.push(...greatItems);

	// Learnsets no teambuilder table.
	// O cliente usa Array.includes('a') para verificar legal em gen 9 standard, e Array.includes('9') para
	// o filtro de gen. Os códigos do servidor usam "9M","9L5" etc, sem os tokens avulsos '9' e 'a'.
	// Por isso transformamos: se o entry tem algum código "9...", adicionamos '9' e 'a' como tokens extras.
	const Learnsets = requireNoCache(path.join(serverRoot, 'dist/data/learnsets.js')).Learnsets;
	BattleTeambuilderTable.learnsets = {};
	for (const id in Learnsets) {
		if (!Learnsets[id].learnset) continue;
		const learnset = {};
		for (const moveid in Learnsets[id].learnset) {
			const entry = [...Learnsets[id].learnset[moveid]];
			const hasGen9 = entry.some(e => e.charAt(0) === '9');
			if (hasGen9) {
				if (!entry.includes('9')) entry.push('9');
				if (!entry.includes('a')) entry.push('a');
			}
			learnset[moveid] = entry;
		}
		BattleTeambuilderTable.learnsets[id] = learnset;
	}

	buf += 'exports.BattleTeambuilderTable = ' + JSON.stringify(BattleTeambuilderTable) + ';\n';

	fs.writeFileSync('play.pokemonshowdown.com/data/teambuilder-tables.js', buf);
}


console.log("DONE");

/*********************************************************
 * Build pokedex.js
 *********************************************************/

process.stdout.write("Building `data/pokedex.js`... ");

{
	const Pokedex = requireNoCache(path.join(serverRoot, 'dist/data/pokedex.js')).Pokedex;
	for (const id in Pokedex) {
		const entry = Pokedex[id];
		if (Dex.data.FormatsData[id]) {
			// console.log('formatsentry:' + id);
			const formatsEntry = Dex.data.FormatsData[id];
			if (formatsEntry.tier) entry.tier = formatsEntry.tier;
			if (formatsEntry.isNonstandard) entry.isNonstandard = formatsEntry.isNonstandard;
			if (formatsEntry.unreleasedHidden) entry.unreleasedHidden = formatsEntry.unreleasedHidden;
		}
	}
	const buf = 'exports.BattlePokedex = ' + es3stringify(Pokedex) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/pokedex.js', buf);
	fs.writeFileSync('play.pokemonshowdown.com/data/pokedex.json', JSON.stringify(Pokedex));
}

console.log("DONE");

/*********************************************************
 * Build moves.js
 *********************************************************/

process.stdout.write("Building `data/moves,items,abilities,typechart,learnsets.js`...");

{
	const Moves = requireNoCache(path.join(serverRoot, 'dist/data/moves.js')).Moves;
	for (const id in Moves) {
		const move = Dex.moves.get(Moves[id].name);
		if (move.desc) Moves[id].desc = move.desc;
		if (move.shortDesc) Moves[id].shortDesc = move.shortDesc;
		if (move.basePowerCallback) Moves[id].basePowerCallback = true;
	}
	const buf = 'exports.BattleMovedex = ' + es3stringify(Moves) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/moves.js', buf);
	fs.writeFileSync('play.pokemonshowdown.com/data/moves.json', JSON.stringify(Moves));
}

/*********************************************************
 * Build items.js
 *********************************************************/

{
	const Items = requireNoCache(path.join(serverRoot, 'dist/data/items.js')).Items;
	for (const id in Items) {
		const item = Dex.items.get(Items[id].name);
		if (item.desc) Items[id].desc = item.desc;
		if (item.shortDesc) Items[id].shortDesc = item.shortDesc;
	}
	const buf = 'exports.BattleItems = ' + es3stringify(Items) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/items.js', buf);
}

/*********************************************************
 * Build abilities.js
 *********************************************************/

{
	const Abilities = requireNoCache(path.join(serverRoot, 'dist/data/abilities.js')).Abilities;
	for (const id in Abilities) {
		const ability = Dex.abilities.get(Abilities[id].name);
		if (ability.desc) Abilities[id].desc = ability.desc;
		if (ability.shortDesc) Abilities[id].shortDesc = ability.shortDesc;
	}
	const buf = 'exports.BattleAbilities = ' + es3stringify(Abilities) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/abilities.js', buf);
}

/*********************************************************
 * Build typechart.js
 *********************************************************/

{
	const TypeChart = requireNoCache(path.join(serverRoot, 'dist/data/typechart.js')).TypeChart;
	const buf = 'exports.BattleTypeChart = ' + es3stringify(TypeChart) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/typechart.js', buf);
}

/*********************************************************
 * Build aliases.js
 *********************************************************/

{
	const Aliases = requireNoCache(path.join(serverRoot, 'dist/data/aliases.js')).Aliases;
	const buf = 'exports.BattleAliases = ' + es3stringify(Aliases) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/aliases.js', buf);
}

/*********************************************************
 * Build formats-data.js
 *********************************************************/

{
	const FormatsData = requireNoCache(path.join(serverRoot, 'dist/data/formats-data.js')).FormatsData;
	const buf = 'exports.BattleFormatsData = ' + es3stringify(FormatsData) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/formats-data.js', buf);
}

/*********************************************************
 * Build formats.js
 *********************************************************/

{
	const Formats = requireNoCache(path.join(serverRoot, 'dist/config/formats.js')).Formats;
	const buf = 'exports.Formats = ' + es3stringify(Formats) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/formats.js', buf);
}

/*********************************************************
 * Build learnsets.js
 *********************************************************/

{
	const Learnsets = requireNoCache(path.join(serverRoot, 'dist/data/learnsets.js')).Learnsets;
	const buf = 'exports.BattleLearnsets = ' + es3stringify(Learnsets) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/learnsets.js', buf);
	fs.writeFileSync('play.pokemonshowdown.com/data/learnsets.json', JSON.stringify(Learnsets));
}

/*********************************************************
 * Build text.js
 *********************************************************/

{
	const textData = Dex.loadTextData();
	const Text = textData.Default;

	function assignData(id, entry) {
		for (const key in entry) {
			if (['name', 'desc', 'shortDesc'].includes(key)) continue;
			const textEntry = Text[id] || (Text[id] = {});
			if (key.startsWith('gen')) {
				for (const modKey in entry[key]) {
					if (['desc', 'shortDesc'].includes(key)) continue;
					textEntry[modKey + 'Gen' + key.charAt(3)] = entry[key][modKey];
				}
			} else {
				textEntry[key] = entry[key];
			}
		}
	}

	for (const id in textData.Moves) assignData(id, textData.Moves[id]);
	for (const id in textData.Abilities) assignData(id, textData.Abilities[id]);
	for (const id in textData.Items) assignData(id, textData.Items[id]);

	const buf = 'exports.BattleText = ' + es3stringify(Text) + ';';
	fs.writeFileSync('play.pokemonshowdown.com/data/text.js', buf);
}

console.log("DONE");
